### ISSUE TITLE
Cannot sync with multi tabs by built-in broadcast channel

### ISSUE THREAD

**Issue by IndexXuan** [ivan-topp/y-socket.io#3]
Thanks for the y-socket.io.

But when I open 2 Tabs in Chrome and do something, It isn't synced with each other.
According to y-websocket, I think when bc connected, y-socket.io missing a `step-2` bc.publish.

https://github.com/yjs/y-websocket/blob/master/src/y-websocket.js#L430
https://github.com/ivan-topp/y-socket.io/blob/main/src/client/provider.ts#L397

after adding step-2 publish, I works like y-websocket & y-webrtc

**Comment by ivan-topp** [comment]
Ooh, you are absolutely right, now I just fixed this problem, the new version is now available.

Thank you very much
